# Generated by Django 5.1.4 on 2025-01-10 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0002_user_phone_number_user_profile_pic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_pic",
            field=models.ImageField(
                blank=True,
                default="profile_pics/default.jpg",
                null=True,
                upload_to="profile_pics/",
            ),
        ),
    ]
