# Generated by Django 5.1.4 on 2025-01-11 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0005_subject_grade_course"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="grade",
        ),
        migrations.RemoveField(
            model_name="course",
            name="students",
        ),
        migrations.RemoveField(
            model_name="course",
            name="subject",
        ),
        migrations.RemoveField(
            model_name="course",
            name="teacher",
        ),
        migrations.RemoveField(
            model_name="grade",
            name="class_teacher",
        ),
        migrations.RemoveField(
            model_name="grade",
            name="school",
        ),
        migrations.RemoveField(
            model_name="useractivitylog",
            name="user",
        ),
        migrations.AddConstraint(
            model_name="student",
            constraint=models.UniqueConstraint(
                fields=("user", "school"), name="unique_student_school"
            ),
        ),
        migrations.AddConstraint(
            model_name="teacher",
            constraint=models.UniqueConstraint(
                fields=("user", "school"), name="unique_teacher_school"
            ),
        ),
        migrations.DeleteModel(
            name="Subject",
        ),
        migrations.DeleteModel(
            name="Course",
        ),
        migrations.DeleteModel(
            name="Grade",
        ),
        migrations.DeleteModel(
            name="UserActivityLog",
        ),
    ]
